StylesPath = <path of your locally cloned folder without spaces>

# List of packages used and will be updated when doing Vale sync.
Packages = Microsoft, write-good

IgnoredScopes = code, tt

# Company-specific vocabulary that acts as additional allowances or exception to the standard rules.
Vocab = Kore

# Values can be suggestion, warning, or error.
MinAlertLevel = suggestion 

# Only specific files formats are checked. SVG, PNG, etc. are not checked.
[*.md]
BasedOnStyles = Microsoft

[*.txt]
BasedOnStyles = Microsoft

[*.mdx]
BasedOnStyles = Microsoft

# Commented list of checks that I suppressed earlier -- do NOT uncomment these.

; Microsoft.Acronyms = NO
; Microsoft.Quotes = NO
; Microsoft.Vocab = NO
; Microsoft.Headings = NO
; Microsoft.Contractions = NO
; Microsoft.Wordiness = NO

# Ignore SVG markup as a preventive thing, although .svg format isn't checked.
TokenIgnores = (\*\*\{\w*\}\*\*)